---

base_locale: en
locales: [en]

data:
  external:
    - "<%= %x[bundle info decidim-core --path].chomp %>/config/locales/%{locale}.yml"
    - "<%= %x[bundle info decidim-admin --path].chomp %>/config/locales/%{locale}.yml"
    - "<%= %x[bundle info decidim-participatory_processes --path].chomp %>/config/locales/%{locale}.yml"
    - "<%= %x[bundle info decidim-elections --path].chomp %>/config/locales/%{locale}.yml"
    - "<%= %x[bundle info decidim-verifications --path].chomp %>/config/locales/%{locale}.yml"

ignore_unused:
  - "layouts.decidim.user_profile.vote_delegations"
  - "devise.mailer.*"
  - "decidim.verifications.authorizations.first_login.*"
  - "decidim.authorization_handlers.*"
  - "decidim.admin.actions.invite_all"
  - "activemodel.attributes.*"
  - "activemodel.errors.*"
  - "decidim.action_delegator.participants_csv_importer.import.*"
  - "decidim.action_delegator.admin.settings.authorization_method.*"
  - "decidim.action_delegator.admin.invite_participants.*"
  - "decidim.action_delegator.invite_participants_mailer.*"
  - "decidim.action_delegator.admin.delegations.csv_imports.*"
  - "decidim.action_delegator.admin.menu.*"
  - "decidim.action_delegator.verification.admin.members.index.*"
  - "decidim.action_delegator.verifications.delegations_verifier*"
  - "decidim.action_delegator.import_mailer.*"
  - "decidim.action_delegator.delegations_authorizer.*"
  - "decidim.action_delegator.admin.manage*"
  - "decidim.action_delegator.admin.participants.*"
  - "decidim.action_delegator.admin.permissions.*"
  - "decidim.action_delegator.admin.ponderations.index.*"
  - "decidim.action_delegator.admin.settings.*"
  - "decidim.action_delegator.admin.weighted_results.title"
  - "decidim.action_delegator.authorizations.*"
  - "decidim.action_delegator.delegations.*"
